import {
  defineCommand,
  createDeployment,
  pickPlanStrategy,
  STRATEGIES,
  defaultDeployPlan,
  hasPrepaidFlags,
  type DeployModality,
  type CreateDeploymentRequest,
  type CommandContext,
  type CommandRisk,
  type FlagsDef,
  type ParsedFlags,
} from "bailian-cli-core";
import { emitResult, emitBare } from "bailian-cli-runtime";
import {
  CAPACITY_FLAGS,
  PREPAID_FLAGS,
  WAIT_OPTIONS,
  finishMutation,
  validateWriteOptions,
} from "./mutation-shared.ts";

const CREATE_FLAGS = {
  modelName: {
    type: "string",
    valueHint: "<model_name>",
    description: {
      "en-US": "Model to deploy — fine-tuned output name or catalog model (required)",
      "zh-CN": "要部署的模型：微调输出模型名称或模型目录中的模型（必填）",
    },
    required: true,
  },
  displayName: {
    type: "string",
    valueHint: "<display_name>",
    description: {
      "en-US": "Console display name (optional for PTU; required for other plans)",
      "zh-CN": "控制台显示名称（PTU 可选；其他方案必填）",
    },
  },
  plan: {
    type: "string",
    valueHint: "<plan>",
    description: {
      "en-US": "Billing plan: lora (default, Token-billed) | ptu (throughput reservation) | mu",
      "zh-CN": "计费方案：lora（默认，按 Token 计费）| ptu（吞吐预留）| mu",
    },
  },
  deploySpec: {
    type: "string",
    valueHint: "<id>",
    description: {
      "en-US": "Deploy spec (only used by plan=mu; auto-picked if omitted)",
      "zh-CN": "部署规格（仅 plan=mu 使用；省略时自动选择）",
    },
  },
  capacity: {
    type: "number",
    valueHint: "<n>",
    description: {
      "en-US": "Resource units (plan=mu only; required by API; defaults to the template's unit)",
      "zh-CN": "资源单元数（仅 plan=mu；API 必填；默认为模板的单元数）",
    },
  },
  billingMethod: {
    type: "string",
    valueHint: "<m>",
    description: {
      "en-US": 'Billing method (plan=mu only; default "POST_PAY", the only supported value)',
      "zh-CN": '计费方式（仅 plan=mu；默认且仅支持 "POST_PAY"）',
    },
  },
  ...CAPACITY_FLAGS,
  thinkingOutputTpm: {
    type: "number",
    valueHint: "<n>",
    description: {
      "en-US": "Legacy thinking-output capacity flag; not supported for PTU",
      "zh-CN": "旧版思考输出容量参数；PTU 不支持此参数",
    },
  },
  chargeType: {
    type: "string",
    valueHint: "<type>",
    choices: ["pre_paid", "post_paid"] as const,
    description: {
      "en-US": "PTU payment type (required for plan=ptu): pre_paid or post_paid",
      "zh-CN": "PTU 付费方式（plan=ptu 必填）：pre_paid 或 post_paid",
    },
  },
  serviceTier: {
    type: "string",
    valueHint: "<tier>",
    choices: ["ptu_fast", "ptu_default"] as const,
    description: {
      "en-US": "PTU service tier: ptu_fast (default) or ptu_default (prepaid only)",
      "zh-CN": "PTU 性能档位：ptu_fast（默认高速）或 ptu_default（标速，仅预付费）",
    },
  },
  suffix: {
    type: "string",
    valueHint: "<suffix>",
    description: {
      "en-US": "Optional PTU ModelCode suffix; generated by the service when omitted",
      "zh-CN": "可选 PTU ModelCode 后缀；省略时由服务端生成",
    },
  },
  ...PREPAID_FLAGS,
  ...WAIT_OPTIONS,
} satisfies FlagsDef;

const CREATE_USAGE =
  "--model-name <model_name> [--display-name <display_name>] [--plan <plan>] [--charge-type <type>] [--service-tier <tier>] [--suffix <suffix>] [--input-tpm <n> --output-tpm <n>] [flags]";

const CREATE_RISK: CommandRisk = {
  level: "high",
  message: {
    "en-US": "Creating a deployment purchases or provisions resources and may incur charges.",
    "zh-CN": "创建部署会购买或开通资源，可能产生费用。",
  },
};

const CREATE_NOTES = [
  {
    "en-US":
      "Plan defaults to `lora` (Token-billed) for text/image and `mu` (model-unit-billed) for audio (CosyVoice TTS). Pass --plan to override.",
    "zh-CN":
      "文本和图片部署默认使用 `lora`（按 Token 计费），音频（CosyVoice TTS）默认使用 `mu`（按模型单元计费）。可通过 --plan 覆盖。",
  },
  {
    "en-US":
      "For plan=ptu, --charge-type, --input-tpm and --output-tpm are required. Capacity is in kTPM (1 kTPM = 1000 tokens/minute). Separate thinking-output capacity is unsupported. Prepaid requires --duration and explicit --auto-renewal true|false.",
    "zh-CN":
      "plan=ptu 时，--charge-type、--input-tpm 和 --output-tpm 必填。容量单位为 kTPM（1 kTPM = 1000 Token/分钟），不支持单独的思考输出容量。预付费须提供 --duration 和显式 --auto-renewal true|false。",
  },
  {
    "en-US":
      "For plan=mu, `capacity`, `billing_method` and `deploy_spec` are required. billing_method defaults to POST_PAY (only supported value); deploy_spec and capacity are auto-picked from GET /deployments/models when omitted.",
    "zh-CN":
      "plan=mu 时，`capacity`、`billing_method` 和 `deploy_spec` 必填。billing_method 默认且仅支持 POST_PAY；省略 deploy_spec 和 capacity 时，会从 GET /deployments/models 自动选择。",
  },
  {
    "en-US": "Use `deploy models --source base` to inspect available templates.",
    "zh-CN": "使用 `deploy models --source base` 查看可用模板。",
  },
  {
    "en-US":
      "PTU creation preserves the original JSON and operation_id even with --quiet. --wait only queries the returned operation; pending capacity is not effective capacity. Check the actual status before invoking the model.",
    "zh-CN":
      "PTU 创建即使指定 --quiet 也保留原始 JSON 和 operation_id。--wait 仅查询返回的操作；待生效容量不等于已生效容量。调用模型前请确认实际状态。",
  },
  {
    "en-US":
      "--model-name identifies the source model; the returned deployed_model is the invocation identifier (ModelCode). Use it for inference (`text chat --model <deployed_model>`) and deployment lifecycle commands.",
    "zh-CN":
      "--model-name 标识源模型；返回的 deployed_model 为调用标识（ModelCode），用于推理（`text chat --model <deployed_model>`）和部署生命周期命令。",
  },
  {
    "en-US":
      "Initial ModelCode creation does not support --request-id or promise idempotency. A timeout is not proof of failure: check whether the deployment was created before trying again. This command never automatically resubmits creation.",
    "zh-CN":
      "首次创建 ModelCode 不支持 --request-id，也不承诺幂等。超时不代表失败：再次尝试前先确认部署是否已创建。本命令不会自动重新提交创建请求。",
  },
  {
    "en-US":
      "Use --dry-run to preview without requests. Pass --yes only after confirming the costs.",
    "zh-CN": "使用 --dry-run 离线预览；仅在确认费用后传入 --yes 执行。",
  },
];

function validateCreate(
  modality: DeployModality,
  flags: ParsedFlags<typeof CREATE_FLAGS>,
): string | undefined {
  const plan = flags.plan || defaultDeployPlan(modality);
  const strategy = STRATEGIES[plan];
  if (!strategy) {
    return `Unsupported plan "${plan}". Supported plans: ${Object.keys(STRATEGIES).join(", ")}. / 不支持方案 "${plan}"；支持的方案：${Object.keys(STRATEGIES).join(", ")}。`;
  }
  if (plan !== "ptu") {
    if (
      flags.chargeType !== undefined ||
      flags.serviceTier !== undefined ||
      flags.suffix !== undefined ||
      hasPrepaidFlags(flags) ||
      flags.wait ||
      flags.interval !== undefined ||
      flags.pollTimeout !== undefined
    ) {
      return "Payment, service tier, suffix, prepaid and wait options are PTU-only. / 付费方式、性能档位、后缀、预付费和等待参数仅适用于 PTU。";
    }
    if (!flags.displayName?.trim()) {
      return "--display-name is required for non-PTU plans. / 非 PTU 方案必须提供 --display-name。";
    }
  } else if (flags.thinkingOutputTpm !== undefined) {
    return "--thinking-output-tpm is not supported for PTU. / PTU 不支持 --thinking-output-tpm。";
  }
  return validateWriteOptions(flags) ?? strategy.validateFlags(flags);
}

/** Shared create implementation; plan-specific body assembly remains in core. */
async function runCreate(
  modality: DeployModality,
  ctx: CommandContext<typeof CREATE_FLAGS>,
): Promise<void> {
  const { identity, settings, flags } = ctx;
  const plan = flags.plan || defaultDeployPlan(modality);
  const strategy = pickPlanStrategy(plan);
  const resolveBody = async (dryRun: boolean): Promise<CreateDeploymentRequest> => {
    const resolved = await strategy.resolve({
      client: ctx.client,
      dryRun,
      binName: identity.binName,
      flags,
      model: flags.modelName,
      name: flags.displayName,
    });
    return {
      model_name: flags.modelName,
      ...(flags.displayName !== undefined ? { name: flags.displayName } : {}),
      plan,
      ...resolved.body,
    };
  };

  // A dry strategy resolution must precede any catalog lookup or write.
  if (settings.dryRun) {
    emitResult({ action: "deploy.create", body: await resolveBody(true) }, "json");
    return;
  }

  const response = await createDeployment(ctx.client, await resolveBody(false));
  const deployment = response.output ?? response.data;
  if (plan === "ptu") {
    await finishMutation(ctx.client, deployment?.deployed_model, response, flags);
  } else if (settings.quiet) {
    emitBare(deployment?.deployed_model ?? "");
  } else {
    emitResult(response, "json");
  }
}

/** `bl deploy text create` — deploy a text model. */
export const deployTextCreate = defineCommand({
  description: { "en-US": "Create a text model deployment", "zh-CN": "创建文本模型部署" },
  auth: "apiKey",
  risk: CREATE_RISK,
  usageArgs: CREATE_USAGE,
  flags: CREATE_FLAGS,
  exampleArgs: [
    "--model-name my-qwen-sft --display-name my-sft-test",
    "--model-name qwen3.6-flash-2026-04-16 --plan ptu --charge-type post_paid --input-tpm 10000 --output-tpm 1000 --dry-run",
    "--model-name qwen3.6-flash-2026-04-16 --plan ptu --charge-type pre_paid --service-tier ptu_default --input-tpm 10000 --output-tpm 1000 --duration 30 --auto-renewal false --dry-run",
    "--model-name qwen3-8b --display-name my-qwen3-mu --plan mu",
    "--model-name qwen3-8b --display-name my-qwen3 --plan mu --deploy-spec MU1 --capacity 2",
  ],
  notes: CREATE_NOTES,
  validate: (flags) => validateCreate("text", flags),
  run: (ctx) => runCreate("text", ctx),
});

/** `bl deploy audio create` — deploy an audio (TTS) model. Defaults to plan=mu. */
export const deployAudioCreate = defineCommand({
  description: {
    "en-US": "Create an audio (TTS) model deployment",
    "zh-CN": "创建音频（TTS）模型部署",
  },
  auth: "apiKey",
  risk: CREATE_RISK,
  usageArgs: CREATE_USAGE,
  flags: CREATE_FLAGS,
  exampleArgs: [
    "--model-name my-cosyvoice-ft --display-name my-tts",
    "--model-name my-cosyvoice-ft --display-name my-tts --deploy-spec dps-xxxx --capacity 1",
    "--model-name my-cosyvoice-ft --display-name my-tts --dry-run",
  ],
  notes: CREATE_NOTES,
  validate: (flags) => validateCreate("audio", flags),
  run: (ctx) => runCreate("audio", ctx),
});

/** `bl deploy image create` — deploy an image generation model. */
export const deployImageCreate = defineCommand({
  description: {
    "en-US": "Create an image generation model deployment",
    "zh-CN": "创建图片生成模型部署",
  },
  auth: "apiKey",
  risk: CREATE_RISK,
  usageArgs: CREATE_USAGE,
  flags: CREATE_FLAGS,
  exampleArgs: [
    "--model-name my-wan-ft --display-name my-wan",
    "--model-name my-wan-ft --display-name my-wan-mu --plan mu",
    "--model-name my-wan-ft --display-name my-wan --dry-run",
  ],
  notes: CREATE_NOTES,
  validate: (flags) => validateCreate("image", flags),
  run: (ctx) => runCreate("image", ctx),
});
