import type { AnyCommand } from "bailian-cli-core";
import {
  configShow,
  configSet,
  update,
  knowledgeRetrieve,
  knowledgeSearch,
  knowledgeChat,
  knowledgeKbList,
  knowledgeKbInfo,
  knowledgeDocList,
  knowledgeDocStatus,
  knowledgeDocUpload,
  knowledgeKbCreate,
  knowledgeKbUpdate,
  knowledgeKbDelete,
  knowledgeDocDelete,
  knowledgeDocTag,
  knowledgeServiceList,
  knowledgeServiceGet,
  knowledgeServiceCreate,
  knowledgeServiceUpdate,
  knowledgeServiceDeploy,
  knowledgeServiceDelete,
  knowledgeServiceCopy,
  knowledgeChunkAdd,
  knowledgeChunkList,
  knowledgeChunkUpdate,
  knowledgeChunkDelete,
  knowledgeKbStats,
  knowledgeCategoryList,
  knowledgeCategoryAdd,
  knowledgeCategoryDelete,
  knowledgeFileList,
  knowledgeFileGet,
  knowledgeFileDelete,
  knowledgeCollectionCreate,
  knowledgeCollectionGet,
  knowledgeDocImportOss,
} from "bailian-cli-commands";

// kscli (Knowledge Studio CLI): lightweight RAG product. Ships config/update
// plus the knowledge commands, remapped to flat paths. Routing is driven
// entirely by these keys, and usage/examples/errors render the path from the
// key — so the same shared command shows `kscli search` here and
// `bl knowledge search` in bl.
export const commands: Record<string, AnyCommand> = {
  "config show": configShow,
  "config set": configSet,
  update,
  retrieve: knowledgeRetrieve,
  search: knowledgeSearch,
  chat: knowledgeChat,
  "kb list": knowledgeKbList,
  "kb info": knowledgeKbInfo,
  "kb create": knowledgeKbCreate,
  "kb update": knowledgeKbUpdate,
  "kb delete": knowledgeKbDelete,
  "doc list": knowledgeDocList,
  "doc status": knowledgeDocStatus,
  "doc upload": knowledgeDocUpload,
  "doc delete": knowledgeDocDelete,
  "doc tag": knowledgeDocTag,
  "service list": knowledgeServiceList,
  "service get": knowledgeServiceGet,
  "service create": knowledgeServiceCreate,
  "service update": knowledgeServiceUpdate,
  "service deploy": knowledgeServiceDeploy,
  "service delete": knowledgeServiceDelete,
  "service copy": knowledgeServiceCopy,
  "chunk add": knowledgeChunkAdd,
  "chunk list": knowledgeChunkList,
  "chunk update": knowledgeChunkUpdate,
  "chunk delete": knowledgeChunkDelete,
  "kb stats": knowledgeKbStats,
  "category list": knowledgeCategoryList,
  "category add": knowledgeCategoryAdd,
  "category delete": knowledgeCategoryDelete,
  "file list": knowledgeFileList,
  "file get": knowledgeFileGet,
  "file delete": knowledgeFileDelete,
  "collection create": knowledgeCollectionCreate,
  "collection get": knowledgeCollectionGet,
  "doc import-oss": knowledgeDocImportOss,
};
