import type { AnyCommand } from "bailian-cli-core";
import {
  authLogin,
  authStatus,
  authLogout,
  authGenerateAccessToken,
  textChat,
  textOmni,
  imageGenerate,
  imageEdit,
  videoGenerate,
  videoEdit,
  videoRef,
  videoTaskGet,
  videoDownload,
  visionDescribe,
  configShow,
  configSet,
  configList,
  configUse,
  configUi,
  configAgent,
  update,
  appCall,
  appList,
  memoryAdd,
  memorySearch,
  memoryList,
  memoryUpdate,
  memoryDelete,
  memoryProfileCreate,
  memoryProfileGet,
  knowledgeRetrieve,
  knowledgeSearch,
  knowledgeChat,
  knowledgeKbList,
  knowledgeKbInfo,
  knowledgeDocList,
  knowledgeDocStatus,
  knowledgeDocUpload,
  knowledgeKbCreate,
  knowledgeKbUpdate,
  knowledgeKbDelete,
  knowledgeDocDelete,
  knowledgeDocTag,
  knowledgeServiceList,
  knowledgeServiceGet,
  knowledgeServiceCreate,
  knowledgeServiceUpdate,
  knowledgeServiceDeploy,
  knowledgeServiceDelete,
  knowledgeServiceCopy,
  knowledgeChunkAdd,
  knowledgeChunkList,
  knowledgeChunkUpdate,
  knowledgeChunkDelete,
  knowledgeKbStats,
  knowledgeCategoryList,
  knowledgeCategoryAdd,
  knowledgeCategoryDelete,
  knowledgeFileList,
  knowledgeFileGet,
  knowledgeFileDelete,
  knowledgeCollectionCreate,
  knowledgeCollectionGet,
  knowledgeDocImportOss,
  mcpCall,
  mcpList,
  mcpTools,
  searchWeb,
  speechSynthesize,
  speechRecognize,
  fileUpload,
  consoleCall,
  usageFree,
  usageFreetier,
  usageStats,
  usageSummary,
  pipelineRun,
  pipelineValidate,
  advisorRecommend,
  modelList,
  workspaceList,
  quotaList,
  quotaRequest,
  quotaHistory,
  quotaCheck,
  datasetUpload,
  datasetList,
  datasetGet,
  datasetDelete,
  datasetValidate,
  finetuneTextCreate,
  finetuneAudioCreate,
  finetuneImageCreate,
  finetuneList,
  finetuneGet,
  finetuneCancel,
  finetuneDelete,
  finetuneLogs,
  finetuneCheckpoints,
  finetuneExport,
  finetuneWatch,
  finetuneCapability,
  deployTextCreate,
  deployAudioCreate,
  deployImageCreate,
  deployList,
  deployGet,
  deployModels,
  deployScale,
  deployUpdate,
  deployDelete,
  tokenPlanListSeats,
  tokenPlanCreateKey,
  tokenPlanAssignSeats,
  tokenPlanAddMember,
  workspaceInit,
  pluginInstall,
  pluginLink,
  pluginList,
  pluginRemove,
  skillAdd,
  skillUpdate,
  skillRemove,
  skillList,
  managedAgentInit,
  managedAgentValidate,
  managedAgentPlan,
  managedAgentApply,
  managedAgentDestroy,
  managedAgentStateList,
  managedAgentStateShow,
  managedAgentStateRm,
  managedAgentStateImport,
  managedAgentSessionCreate,
  managedAgentSessionList,
  managedAgentSessionGet,
  managedAgentSessionDelete,
  managedAgentSessionRun,
  managedAgentSessionSend,
  managedAgentSessionEvents,
  managedAgentSkillList,
} from "bailian-cli-commands";

// Full bailian-cli product: every command, exposed under the `bl` binary.
// The command paths below are this product's decision — the command library
// ships no presets, so the map is spelled out here. Kept in its own module
// (no side effects) so tools like generate-reference.ts can import it without
// starting the CLI.
export const commands: Record<string, AnyCommand> = {
  "auth login": authLogin,
  "auth status": authStatus,
  "auth logout": authLogout,
  "auth generate-access-token": authGenerateAccessToken,
  "text chat": textChat,
  omni: textOmni,
  "image generate": imageGenerate,
  "image edit": imageEdit,
  "video generate": videoGenerate,
  "video edit": videoEdit,
  "video ref": videoRef,
  "video task get": videoTaskGet,
  "video download": videoDownload,
  "vision describe": visionDescribe,
  "config show": configShow,
  "config set": configSet,
  "config list": configList,
  "config use": configUse,
  "config ui": configUi,
  "config agent": configAgent,
  update,
  "app call": appCall,
  "app list": appList,
  "memory add": memoryAdd,
  "memory search": memorySearch,
  "memory list": memoryList,
  "memory update": memoryUpdate,
  "memory delete": memoryDelete,
  "memory profile create": memoryProfileCreate,
  "memory profile get": memoryProfileGet,
  "knowledge retrieve": knowledgeRetrieve,
  "knowledge search": knowledgeSearch,
  "knowledge chat": knowledgeChat,
  "knowledge list": knowledgeKbList,
  "knowledge info": knowledgeKbInfo,
  "knowledge create": knowledgeKbCreate,
  "knowledge update": knowledgeKbUpdate,
  "knowledge delete": knowledgeKbDelete,
  "knowledge doc list": knowledgeDocList,
  "knowledge doc status": knowledgeDocStatus,
  "knowledge doc upload": knowledgeDocUpload,
  "knowledge doc delete": knowledgeDocDelete,
  "knowledge doc tag": knowledgeDocTag,
  "knowledge service list": knowledgeServiceList,
  "knowledge service get": knowledgeServiceGet,
  "knowledge service create": knowledgeServiceCreate,
  "knowledge service update": knowledgeServiceUpdate,
  "knowledge service deploy": knowledgeServiceDeploy,
  "knowledge service delete": knowledgeServiceDelete,
  "knowledge service copy": knowledgeServiceCopy,
  "knowledge chunk add": knowledgeChunkAdd,
  "knowledge chunk list": knowledgeChunkList,
  "knowledge chunk update": knowledgeChunkUpdate,
  "knowledge chunk delete": knowledgeChunkDelete,
  "knowledge stats": knowledgeKbStats,
  "knowledge doc import-oss": knowledgeDocImportOss,
  // Data-center commands live under knowledge (no separate connector namespace);
  // the user-facing term for connector is "collection".
  "knowledge collection create": knowledgeCollectionCreate,
  "knowledge collection get": knowledgeCollectionGet,
  "knowledge category list": knowledgeCategoryList,
  "knowledge category add": knowledgeCategoryAdd,
  "knowledge category delete": knowledgeCategoryDelete,
  "knowledge file list": knowledgeFileList,
  "knowledge file get": knowledgeFileGet,
  "knowledge file delete": knowledgeFileDelete,
  "mcp call": mcpCall,
  "mcp list": mcpList,
  "mcp tools": mcpTools,
  "search web": searchWeb,
  "speech synthesize": speechSynthesize,
  "speech recognize": speechRecognize,
  "file upload": fileUpload,
  "console call": consoleCall,
  "usage free": usageFree,
  "usage freetier": usageFreetier,
  "usage stats": usageStats,
  "usage summary": usageSummary,
  "pipeline run": pipelineRun,
  "pipeline validate": pipelineValidate,
  "advisor recommend": advisorRecommend,
  "model list": modelList,
  "workspace list": workspaceList,
  "quota list": quotaList,
  "quota request": quotaRequest,
  "quota history": quotaHistory,
  "quota check": quotaCheck,
  "dataset upload": datasetUpload,
  "dataset list": datasetList,
  "dataset get": datasetGet,
  "dataset delete": datasetDelete,
  "dataset validate": datasetValidate,
  "finetune text create": finetuneTextCreate,
  "finetune audio create": finetuneAudioCreate,
  "finetune image create": finetuneImageCreate,
  "finetune list": finetuneList,
  "finetune get": finetuneGet,
  "finetune cancel": finetuneCancel,
  "finetune delete": finetuneDelete,
  "finetune logs": finetuneLogs,
  "finetune checkpoints": finetuneCheckpoints,
  "finetune export": finetuneExport,
  "finetune watch": finetuneWatch,
  "finetune capability": finetuneCapability,
  "deploy text create": deployTextCreate,
  "deploy audio create": deployAudioCreate,
  "deploy image create": deployImageCreate,
  "deploy list": deployList,
  "deploy get": deployGet,
  "deploy models": deployModels,
  "deploy scale": deployScale,
  "deploy update": deployUpdate,
  "deploy delete": deployDelete,
  "token-plan list-seats": tokenPlanListSeats,
  "token-plan create-key": tokenPlanCreateKey,
  "token-plan assign-seats": tokenPlanAssignSeats,
  "token-plan add-member": tokenPlanAddMember,
  "workspace init": workspaceInit,
  "plugin install": pluginInstall,
  "plugin link": pluginLink,
  "plugin list": pluginList,
  "plugin remove": pluginRemove,
  "skill add": skillAdd,
  "skill update": skillUpdate,
  "skill remove": skillRemove,
  "skill list": skillList,
  "managed-agent init": managedAgentInit,
  "managed-agent validate": managedAgentValidate,
  "managed-agent plan": managedAgentPlan,
  "managed-agent apply": managedAgentApply,
  "managed-agent destroy": managedAgentDestroy,
  "managed-agent state list": managedAgentStateList,
  "managed-agent state show": managedAgentStateShow,
  "managed-agent state rm": managedAgentStateRm,
  "managed-agent state import": managedAgentStateImport,
  "managed-agent session create": managedAgentSessionCreate,
  "managed-agent session list": managedAgentSessionList,
  "managed-agent session get": managedAgentSessionGet,
  "managed-agent session delete": managedAgentSessionDelete,
  "managed-agent session run": managedAgentSessionRun,
  "managed-agent session send": managedAgentSessionSend,
  "managed-agent session events": managedAgentSessionEvents,
  "managed-agent skill-list": managedAgentSkillList,
};
