import type { AnyCommand } from "bailian-cli-core";
import {
  authLogin,
  authStatus,
  authLogout,
  authGenerateAccessToken,
  textChat,
  textOmni,
  imageGenerate,
  imageEdit,
  videoGenerate,
  videoEdit,
  videoRef,
  videoTaskGet,
  videoDownload,
  visionDescribe,
  configShow,
  configSet,
  configList,
  configUse,
  configUi,
  configAgent,
  update,
  appCall,
  appList,
  memoryAdd,
  memorySearch,
  memoryList,
  memoryUpdate,
  memoryDelete,
  memoryProfileCreate,
  memoryProfileGet,
  knowledgeRetrieve,
  knowledgeSearch,
  knowledgeChat,
  knowledgeKbList,
  knowledgeKbInfo,
  knowledgeDocList,
  knowledgeDocStatus,
  knowledgeDocUpload,
  knowledgeKbCreate,
  knowledgeKbUpdate,
  knowledgeKbDelete,
  knowledgeDocDelete,
  knowledgeDocTag,
  knowledgeServiceList,
  knowledgeServiceGet,
  knowledgeServiceCreate,
  knowledgeServiceUpdate,
  knowledgeServiceDeploy,
  knowledgeServiceDelete,
  knowledgeServiceCopy,
  knowledgeChunkAdd,
  knowledgeChunkList,
  knowledgeChunkUpdate,
  knowledgeChunkDelete,
  knowledgeKbStats,
  knowledgeCategoryList,
  knowledgeCategoryAdd,
  knowledgeCategoryDelete,
  knowledgeFileList,
  knowledgeFileGet,
  knowledgeFileDelete,
  knowledgeCollectionCreate,
  knowledgeCollectionGet,
  knowledgeDocImportOss,
  mcpCall,
  mcpList,
  mcpTools,
  searchWeb,
  speechSynthesize,
  speechRecognize,
  fileUpload,
  consoleCall,
  usageFree,
  usageFreetier,
  usageStats,
  usageSummary,
  usageTokenPlan,
  usageCodingPlan,
  pipelineRun,
  pipelineValidate,
  advisorRecommend,
  modelList,
  workspaceList,
  quotaList,
  quotaUpdate,
  quotaDelete,
  quotaHistory,
  quotaCheck,
  permissionList,
  permissionGrant,
  permissionRevoke,
  datasetUpload,
  datasetList,
  datasetGet,
  datasetDelete,
  datasetValidate,
  finetuneTextCreate,
  finetuneAudioCreate,
  finetuneImageCreate,
  finetuneVideoCreate,
  finetuneList,
  finetuneGet,
  finetuneCancel,
  finetuneDelete,
  finetuneLogs,
  finetuneCheckpoints,
  finetuneExport,
  finetuneWatch,
  finetuneCapability,
  finetunePrice,
  deployTextCreate,
  deployAudioCreate,
  deployImageCreate,
  deployList,
  deployGet,
  deployModels,
  deployScale,
  deployUpdate,
  deployDelete,
  deployPause,
  deployResume,
  tokenPlanListSeats,
  tokenPlanCreateKey,
  tokenPlanAssignSeats,
  tokenPlanAddMember,
  workspaceInit,
  pluginInstall,
  pluginLink,
  pluginList,
  pluginRemove,
  skillAdd,
  skillUpdate,
  skillRemove,
  skillList,
  skillInit,
  managedAgentInit,
  managedAgentValidate,
  managedAgentPlan,
  managedAgentApply,
  managedAgentDestroy,
  managedAgentPlayground,
  managedAgentProjectInit,
  managedAgentProjectValidate,
  managedAgentProjectBuild,
  managedAgentProjectPublish,
  managedAgentProjectWorkbench,
  managedAgentProjectVersionEnable,
  managedAgentProjectVersionDisable,
  managedAgentProjectVersionStatus,
  managedAgentProjectVersionList,
  managedAgentProjectVersionPreview,
  managedAgentProjectVersionRestore,
  managedAgentStateList,
  managedAgentStateShow,
  managedAgentStateRm,
  managedAgentStateImport,
  managedAgentSessionCreate,
  managedAgentSessionList,
  managedAgentSessionGet,
  managedAgentSessionDelete,
  managedAgentSessionRun,
  managedAgentSessionSend,
  managedAgentSessionEvents,
  managedAgentSkillList,
  managedAgentAgentCreate,
  managedAgentEnvironmentCreate,
  managedAgentSkillCreate,
  managedAgentVaultCreate,
  managedAgentVaultCredentialCreate,
  managedAgentDeploymentCreate,
  managedAgentAgentList,
  managedAgentAgentGet,
  managedAgentAgentSearch,
  managedAgentAgentVersions,
  managedAgentEnvironmentList,
  managedAgentEnvironmentGet,
  managedAgentEnvironmentSearch,
  managedAgentSkillGet,
  managedAgentSkillSearch,
  managedAgentSkillVersions,
  managedAgentSkillDownload,
  managedAgentVaultList,
  managedAgentVaultGet,
  managedAgentVaultSearch,
  managedAgentDeploymentList,
  managedAgentDeploymentGet,
  managedAgentDeploymentSearch,
  managedAgentDeploymentRunsList,
  managedAgentDeploymentRunsGet,
  managedAgentDeploymentRun,
  managedAgentDeploymentPause,
  managedAgentDeploymentUnpause,
  managedAgentSessionSearch,
  managedAgentSessionUpdate,
  managedAgentSessionArchive,
  managedAgentSessionEventList,
  managedAgentSessionEventSend,
  managedAgentSessionEventStream,
  managedAgentSessionDebug,
  managedAgentSessionExport,
  managedAgentFileUpload,
  managedAgentFileList,
  managedAgentFileGet,
  managedAgentFileSearch,
  managedAgentFileDownload,
  managedAgentFileDelete,
} from "bailian-cli-commands";

// Full bailian-cli product: every command, exposed under the `bl` binary.
// The command paths below are this product's decision — the command library
// ships no presets, so the map is spelled out here. Kept in its own module
// (no side effects) so tools like generate-reference.ts can import it without
// starting the CLI.
export const commands: Record<string, AnyCommand> = {
  "auth login": authLogin,
  "auth status": authStatus,
  "auth logout": authLogout,
  "auth generate-access-token": authGenerateAccessToken,
  "text chat": textChat,
  omni: textOmni,
  "image generate": imageGenerate,
  "image edit": imageEdit,
  "video generate": videoGenerate,
  "video edit": videoEdit,
  "video ref": videoRef,
  "video task get": videoTaskGet,
  "video download": videoDownload,
  "vision describe": visionDescribe,
  "config show": configShow,
  "config set": configSet,
  "config list": configList,
  "config use": configUse,
  "config ui": configUi,
  "config agent": configAgent,
  update,
  "app call": appCall,
  "app list": appList,
  "memory add": memoryAdd,
  "memory search": memorySearch,
  "memory list": memoryList,
  "memory update": memoryUpdate,
  "memory delete": memoryDelete,
  "memory profile create": memoryProfileCreate,
  "memory profile get": memoryProfileGet,
  "knowledge retrieve": knowledgeRetrieve,
  "knowledge search": knowledgeSearch,
  "knowledge chat": knowledgeChat,
  "knowledge list": knowledgeKbList,
  "knowledge info": knowledgeKbInfo,
  "knowledge create": knowledgeKbCreate,
  "knowledge update": knowledgeKbUpdate,
  "knowledge delete": knowledgeKbDelete,
  "knowledge doc list": knowledgeDocList,
  "knowledge doc status": knowledgeDocStatus,
  "knowledge doc upload": knowledgeDocUpload,
  "knowledge doc delete": knowledgeDocDelete,
  "knowledge doc tag": knowledgeDocTag,
  "knowledge service list": knowledgeServiceList,
  "knowledge service get": knowledgeServiceGet,
  "knowledge service create": knowledgeServiceCreate,
  "knowledge service update": knowledgeServiceUpdate,
  "knowledge service deploy": knowledgeServiceDeploy,
  "knowledge service delete": knowledgeServiceDelete,
  "knowledge service copy": knowledgeServiceCopy,
  "knowledge chunk add": knowledgeChunkAdd,
  "knowledge chunk list": knowledgeChunkList,
  "knowledge chunk update": knowledgeChunkUpdate,
  "knowledge chunk delete": knowledgeChunkDelete,
  "knowledge stats": knowledgeKbStats,
  "knowledge doc import-oss": knowledgeDocImportOss,
  // Data-center commands live under knowledge (no separate connector namespace);
  // the user-facing term for connector is "collection".
  "knowledge collection create": knowledgeCollectionCreate,
  "knowledge collection get": knowledgeCollectionGet,
  "knowledge category list": knowledgeCategoryList,
  "knowledge category add": knowledgeCategoryAdd,
  "knowledge category delete": knowledgeCategoryDelete,
  "knowledge file list": knowledgeFileList,
  "knowledge file get": knowledgeFileGet,
  "knowledge file delete": knowledgeFileDelete,
  "mcp call": mcpCall,
  "mcp list": mcpList,
  "mcp tools": mcpTools,
  "search web": searchWeb,
  "speech synthesize": speechSynthesize,
  "speech recognize": speechRecognize,
  "file upload": fileUpload,
  "console call": consoleCall,
  "usage free": usageFree,
  "usage freetier": usageFreetier,
  "usage stats": usageStats,
  "usage summary": usageSummary,
  "usage token-plan": usageTokenPlan,
  "usage coding-plan": usageCodingPlan,
  "pipeline run": pipelineRun,
  "pipeline validate": pipelineValidate,
  "advisor recommend": advisorRecommend,
  "model list": modelList,
  "workspace list": workspaceList,
  "quota list": quotaList,
  "quota update": quotaUpdate,
  "quota delete": quotaDelete,
  "quota history": quotaHistory,
  "quota check": quotaCheck,
  "permission list": permissionList,
  "permission grant": permissionGrant,
  "permission revoke": permissionRevoke,
  "dataset upload": datasetUpload,
  "dataset list": datasetList,
  "dataset get": datasetGet,
  "dataset delete": datasetDelete,
  "dataset validate": datasetValidate,
  "finetune text create": finetuneTextCreate,
  "finetune audio create": finetuneAudioCreate,
  "finetune image create": finetuneImageCreate,
  "finetune video create": finetuneVideoCreate,
  "finetune list": finetuneList,
  "finetune get": finetuneGet,
  "finetune cancel": finetuneCancel,
  "finetune delete": finetuneDelete,
  "finetune logs": finetuneLogs,
  "finetune checkpoints": finetuneCheckpoints,
  "finetune export": finetuneExport,
  "finetune watch": finetuneWatch,
  "finetune capability": finetuneCapability,
  "finetune price": finetunePrice,
  "deploy text create": deployTextCreate,
  "deploy audio create": deployAudioCreate,
  "deploy image create": deployImageCreate,
  "deploy list": deployList,
  "deploy get": deployGet,
  "deploy models": deployModels,
  "deploy scale": deployScale,
  "deploy update": deployUpdate,
  "deploy delete": deployDelete,
  "deploy pause": deployPause,
  "deploy resume": deployResume,
  "token-plan list-seats": tokenPlanListSeats,
  "token-plan create-key": tokenPlanCreateKey,
  "token-plan assign-seats": tokenPlanAssignSeats,
  "token-plan add-member": tokenPlanAddMember,
  "workspace init": workspaceInit,
  "plugin install": pluginInstall,
  "plugin link": pluginLink,
  "plugin list": pluginList,
  "plugin remove": pluginRemove,
  "skill add": skillAdd,
  "skill update": skillUpdate,
  "skill remove": skillRemove,
  "skill list": skillList,
  "skill init": skillInit,
  "managed-agent init": managedAgentInit,
  "managed-agent validate": managedAgentValidate,
  "managed-agent plan": managedAgentPlan,
  "managed-agent apply": managedAgentApply,
  "managed-agent destroy": managedAgentDestroy,
  "managed-agent playground": managedAgentPlayground,
  "managed-agent project init": managedAgentProjectInit,
  "managed-agent project validate": managedAgentProjectValidate,
  "managed-agent project build": managedAgentProjectBuild,
  "managed-agent project publish": managedAgentProjectPublish,
  "managed-agent project workbench": managedAgentProjectWorkbench,
  "managed-agent project version enable": managedAgentProjectVersionEnable,
  "managed-agent project version disable": managedAgentProjectVersionDisable,
  "managed-agent project version status": managedAgentProjectVersionStatus,
  "managed-agent project version list": managedAgentProjectVersionList,
  "managed-agent project version preview": managedAgentProjectVersionPreview,
  "managed-agent project version restore": managedAgentProjectVersionRestore,
  "managed-agent state list": managedAgentStateList,
  "managed-agent state show": managedAgentStateShow,
  "managed-agent state rm": managedAgentStateRm,
  "managed-agent state import": managedAgentStateImport,
  "managed-agent session create": managedAgentSessionCreate,
  "managed-agent session list": managedAgentSessionList,
  "managed-agent session get": managedAgentSessionGet,
  "managed-agent session delete": managedAgentSessionDelete,
  "managed-agent session run": managedAgentSessionRun,
  "managed-agent session send": managedAgentSessionSend,
  "managed-agent session events": managedAgentSessionEvents,
  "managed-agent skill-list": managedAgentSkillList,
  "managed-agent agent create": managedAgentAgentCreate,
  "managed-agent agent list": managedAgentAgentList,
  "managed-agent agent get": managedAgentAgentGet,
  "managed-agent agent search": managedAgentAgentSearch,
  "managed-agent agent versions": managedAgentAgentVersions,
  "managed-agent environment create": managedAgentEnvironmentCreate,
  "managed-agent environment list": managedAgentEnvironmentList,
  "managed-agent environment get": managedAgentEnvironmentGet,
  "managed-agent environment search": managedAgentEnvironmentSearch,
  "managed-agent skill create": managedAgentSkillCreate,
  "managed-agent skill list": managedAgentSkillList,
  "managed-agent skill get": managedAgentSkillGet,
  "managed-agent skill search": managedAgentSkillSearch,
  "managed-agent skill versions": managedAgentSkillVersions,
  "managed-agent skill download": managedAgentSkillDownload,
  "managed-agent vault create": managedAgentVaultCreate,
  "managed-agent vault credential create": managedAgentVaultCredentialCreate,
  "managed-agent vault list": managedAgentVaultList,
  "managed-agent vault get": managedAgentVaultGet,
  "managed-agent vault search": managedAgentVaultSearch,
  "managed-agent deployment create": managedAgentDeploymentCreate,
  "managed-agent deployment list": managedAgentDeploymentList,
  "managed-agent deployment get": managedAgentDeploymentGet,
  "managed-agent deployment search": managedAgentDeploymentSearch,
  "managed-agent deployment runs list": managedAgentDeploymentRunsList,
  "managed-agent deployment runs get": managedAgentDeploymentRunsGet,
  "managed-agent deployment run": managedAgentDeploymentRun,
  "managed-agent deployment pause": managedAgentDeploymentPause,
  "managed-agent deployment unpause": managedAgentDeploymentUnpause,
  "managed-agent session search": managedAgentSessionSearch,
  "managed-agent session update": managedAgentSessionUpdate,
  "managed-agent session archive": managedAgentSessionArchive,
  "managed-agent session event list": managedAgentSessionEventList,
  "managed-agent session event send": managedAgentSessionEventSend,
  "managed-agent session event stream": managedAgentSessionEventStream,
  "managed-agent session debug": managedAgentSessionDebug,
  "managed-agent session export": managedAgentSessionExport,
  "managed-agent file upload": managedAgentFileUpload,
  "managed-agent file list": managedAgentFileList,
  "managed-agent file get": managedAgentFileGet,
  "managed-agent file search": managedAgentFileSearch,
  "managed-agent file download": managedAgentFileDownload,
  "managed-agent file delete": managedAgentFileDelete,
};

/**
 * Runtime-only aliases for renamed commands: dispatched by the CLI (merged in
 * main.ts) but kept out of the canonical map so generate-reference.ts only
 * documents the canonical path.
 */
export const commandAliases: Record<string, AnyCommand> = {
  // Pre-migration name of "quota update".
  "quota request": quotaUpdate,
};
