// Command library for bailian-cli products. Exposes the full command set, the
// per-capability groups, and individual command implementations so each
// entrypoint (bl / rag / …) can pick and remap exactly what it needs.

export {
  commands,
  baseCommands,
  knowledgeCommands,
  textCommands,
  mediaCommands,
  memoryCommands,
  miscCommands,
} from "./commands/groups.ts";

// Individual command implementations (for custom path remapping).
export {
  authLogin,
  authStatus,
  authLogout,
  textChat,
  textOmni,
  imageGenerate,
  imageEdit,
  videoGenerate,
  videoEdit,
  videoRef,
  videoTaskGet,
  videoDownload,
  visionDescribe,
  configShow,
  configSet,
  configExportSchema,
  update,
  appCall,
  appList,
  memoryAdd,
  memorySearch,
  memoryList,
  memoryUpdate,
  memoryDelete,
  memoryProfileCreate,
  memoryProfileGet,
  knowledgeRetrieve,
  mcpCall,
  mcpList,
  mcpTools,
  searchWeb,
  speechSynthesize,
  speechRecognize,
  fileUpload,
  consoleCall,
  usageFree,
  usageFreetier,
  usageStats,
  pipelineRun,
  pipelineValidate,
  advisorRecommend,
  workspaceList,
  quotaList,
  quotaRequest,
  quotaHistory,
  quotaCheck,
} from "./commands/groups.ts";
